---
- name: Register public IP
  shell: wget -qO- http://ipecho.net/plain ; echo
  register: host_ip

- debug: msg="My host_ip is {{ host_ip.stdout }}!"

- name: setup A record for test
  route53:
    command: create
    aws_access_key: '{{ encrypted_route53_key }}'
    aws_secret_key: '{{ encrypted_route53_secret }}'
    zone: '{{ansible_nodename}}'
    record: '{{ansible_nodename}}'
    type: A
    ttl: 7200
    value: "{{ host_ip.stdout }}"
    overwrite: true

- name: setup MX record for test
  route53:
    command: create
    aws_access_key: '{{ encrypted_route53_key }}'
    aws_secret_key: '{{ encrypted_route53_secret }}'
    zone: '{{ansible_nodename}}'
    record: '{{ansible_nodename}}'
    type: MX
    ttl: 7200
    value: "10 {{ ansible_nodename }}."
    overwrite: true
    
- name: setup TXT spf record for test
  route53:
    command: create
    aws_access_key: '{{ encrypted_route53_key }}'
    aws_secret_key: '{{ encrypted_route53_secret }}'
    zone: '{{ansible_nodename}}'
    record: '{{ansible_nodename}}'
    type: TXT
    ttl: 7200
    value: '"v=spf1 ip4:{{ host_ip.stdout }} -all"'
    overwrite: true
    
- name: setup TXT domain key for DKIM
  route53:
    command: create
    aws_access_key: '{{ encrypted_route53_key }}'
    aws_secret_key: '{{ encrypted_route53_secret }}'
    zone: '{{ansible_nodename}}'
    record: '_domainkey.{{ansible_nodename}}.'
    type: TXT
    ttl: 7200
    value: '"o=~; r=postmaster@{{ ansible_nodename }}"'
    overwrite: true

- name: Generate DKIM key pair
  shell: "opendkim-genkey -s mail -d {{ ansible_nodename }}"
  tags:
    - dkim

- replace: dest=mail.txt regexp='\n' replace=''
  tags:
    - dkim
    - sed

- name: Process DKIM public key for DNS
  shell: "grep -oe '\"p=\\(.*\\)\"' mail.txt"
  register: dkim_public_key
  tags:
    - dkim
    - sed

- debug: msg="My dkim public key is {{ dkim_public_key.stdout }}!"
  tags:
    - dkim
    - sed
