---
- name: Register public IP
  shell: wget -qO- http://ipecho.net/plain ; echo
  register: host_ip

- debug: msg="My host_ip is {{ host_ip.stdout }} and alaveteli_host is {{ alaveteli_host }}!"

- name: Install packages required by Route53
  apt: name={{ item }} state=present update_cache=True
  with_items:
    - opendkim
    - opendkim-tools
    - python-pip
  tags:
    - apt-get
    - packages

- name: Install boto for route53
  pip: name=boto

- name: setup A record for test
  route53:
    command: create
    aws_access_key: '{{ encrypted_route53_key }}'
    aws_secret_key: '{{ encrypted_route53_secret }}'
    zone: '{{ alaveteli_host }}'
    record: '{{ alaveteli_host }}'
    type: A
    ttl: 7200
    value: "{{ host_ip.stdout }}"
    overwrite: true

- name: setup MX record for test
  route53:
    command: create
    aws_access_key: '{{ encrypted_route53_key }}'
    aws_secret_key: '{{ encrypted_route53_secret }}'
    zone: '{{ alaveteli_host }}'
    record: '{{ alaveteli_host }}'
    type: MX
    ttl: 7200
    value: "10 {{ alaveteli_host }}."
    overwrite: true
    
- name: setup TXT spf record for test
  route53:
    command: create
    aws_access_key: '{{ encrypted_route53_key }}'
    aws_secret_key: '{{ encrypted_route53_secret }}'
    zone: '{{ alaveteli_host }}'
    record: '{{ alaveteli_host }}'
    type: TXT
    ttl: 7200
    value: '"v=spf1 ip4:{{ host_ip.stdout }} -all"'
    overwrite: true
    
- name: setup TXT domain key for DKIM
  route53:
    command: create
    aws_access_key: '{{ encrypted_route53_key }}'
    aws_secret_key: '{{ encrypted_route53_secret }}'
    zone: '{{ alaveteli_host }}'
    record: '_domainkey.{{ alaveteli_host }}.'
    type: TXT
    ttl: 7200
    value: '"o=~; r=postmaster@{{ alaveteli_host }}"'
    overwrite: true

- name: Generate DKIM key pair
  shell: "opendkim-genkey -s mail -d {{ alaveteli_host }}"
  tags:
    - dkim

- replace: dest=mail.txt regexp='\n' replace=''
  tags:
    - dkim

- name: Process DKIM public key for DNS
  shell: "grep -oe 'p=\\(.*\\)\"' mail.txt"
  register: dkim_public_key
  tags:
    - dkim

- name: setup DKIM public DNS key
  route53:
    command: create
    aws_access_key: '{{ encrypted_route53_key }}'
    aws_secret_key: '{{ encrypted_route53_secret }}'
    zone: '{{ alaveteli_host }}'
    record: 'rsa1._domainkey.{{ alaveteli_host }}.'
    type: TXT
    ttl: 7200
    value: '"v=DKIM1; k=rsa; {{ dkim_public_key.stdout }}'
    overwrite: true
  tags:
    - dkim
