---
- name: deploy dns stuff
  route53:
    command: create
    aws_access_key: '{{ encrypted_route53_key }}'
    aws_secret_key: '{{ encrypted_route53_secret }}'
    zone: test.nuvasuparati.info
    record: smtp2.test.nuvasuparati.info
    type: A
    ttl: 7200
    value: 1.1.1.5
    overwrite: true