---
- name: Register public IP
  shell: wget -qO- http://ipecho.net/plain ; echo
  register: host_ip

- debug: msg="My host_ip is {{ host_ip.stdout }}!"

- name: setup A record for test
  route53:
    command: create
    aws_access_key: '{{ encrypted_route53_key }}'
    aws_secret_key: '{{ encrypted_route53_secret }}'
    zone: '{{ansible_nodename}}'
    record: '{{ansible_nodename}}'
    type: A
    ttl: 7200
    value: "{{ host_ip.stdout }}"
    overwrite: true

- name: setup MX record for test
  route53:
    command: create
    aws_access_key: '{{ encrypted_route53_key }}'
    aws_secret_key: '{{ encrypted_route53_secret }}'
    zone: '{{ansible_nodename}}'
    record: '{{ansible_nodename}}'
    type: MX
    ttl: 7200
    value: "10 {{ ansible_nodename }}."
    overwrite: true
