---

language: python

services: postgresql

python: "2.7"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq aptitude python-apt python-pycurl

install:
  - pip install ansible

script:
  - echo localhost > inventory
  - ansible-playbook --syntax-check -i inventory tests/role.yml
  - ansible-playbook -i inventory tests/role.yml --connection=local --sudo -vvvv
  - /usr/sbin/autopostgresqlbackup
