---
# handlers file for alaveteli

- name: reload postfix
  service:
    name: postfix
    state: reloaded

- name: nginx restart
  service:
    name: nginx
    state: restarted

- name: varnish reload
  service:
    name: varnish
    state: reloaded

- name: nginx reload
  service:
    name: nginx
    state: reloaded
