---
- include_vars: encrypted_vars/dnsmadeeasy.yml

- name: DNS setup for morph.io
  dnsmadeeasy: account_key={{ dnsmadeeasy_key }} account_secret={{ dnsmadeeasy_secret }} domain="morph.io" record_ttl=1800 state=present record_name="{{ item.name }}" record_type="{{ item.type }}" record_value='{{ item.value }}'
  tags:
    - dns
  with_items:
    - {type: "A", name: "", value: "50.116.3.88"}
    - {type: "CNAME", name: "www",     value: ""}
    - {type: "CNAME", name: "api",     value: ""}
    - {type: "CNAME", name: "faye",    value: ""}
    - {type: "CNAME", name: "help", value: ""}
    - {type: "CNAME", name: "email",   value: "cuttlefish.io."}
    - {type: "CNAME", name: "email2",  value: "cuttlefish.oaf.org.au."}
    - {type: "MX", name: "", value: "10 aspmx.l.google.com."}
    - {type: "MX", name: "", value: "30 aspmx3.googlemail.com."}
    - {type: "MX", name: "", value: "20 alt2.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "20 alt1.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "30 aspmx2.googlemail.com."}
    - {type: "TXT", name: "", value: '"v=spf1 include:_spf.google.com -all"'}
    - {type: "TXT", name: "", value: "google-site-verification=in8HCE8-6fspAg-ak4TpaWthQ2ix6Ne8sBIzAPwFdDc"}
    - {type: "TXT", name: "cuttlefish._domainkey", value: '"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyo1f2xqD/AeDj2YnQC/xsksEqZ2mxW5hHiRi1jFX7pR0jb1Tf7LVAgj7rtWBxQvjo3xIOZ2wy5z+1hjlN1NDni023O6bFXNY7d/kSqo2E+y8pzReq5qZJu46Ozz88LedU+4/DEnNqSPFbnDjIM5VMEDcw4KhacCDKdNg83yDkKV3x5ugz5K7gRAorYyIxRL4ZQJP0fOWS7""hGpMKYoyJ8hRFdtGAx9yS2wySmUdpKQheQJV63iuSZ4aNcYuWuLULGkhMU8usJVMtwuptEwRHF6+JoOLo+alvya3wgaa0L1sopFKOSYrUGs7zOnIXBGVGbNkg15Ik+1PFGKg05LixJ/QIDAQAB"'}
