# Playbook for backing up your remote instance
---

- hosts: alaveteli
  vars_files:
    - roles/alaveteli/vars/encrypted.yml
    - roles/andreaswolf.letsencrypt/defaults/main.yml

  vars:
    backup_dir: "/tmp/alaveteli"
  tasks:
    - name: Create the backup dir
      file: path={{ backup_dir }} state=directory mode=0755
      delegate_to: localhost

    - name: Pull files from remote to local
      synchronize: src=/srv/www/current/files/ dest={{ backup_dir }}/files mode=pull

    - name: Backup database
      command: "su - postgres -c 'pg_dump alaveteli > /tmp/alaveteli.sql'"

    - name: Pull database backup
      synchronize: src=/tmp/alaveteli.sql dest={{ backup_dir }}/alaveteli.sql mode=pull
