# Playbook for backing up your remote instance
---

- hosts: alaveteli
  vars_files:
    - roles/alaveteli/vars/encrypted.yml
    - roles/alaveteli/vars/main.yml
    - roles/andreaswolf.letsencrypt/defaults/main.yml

  vars:
    backup_dir: "/tmp/alaveteli"
  tasks:
    - name: Create the backup dir
      file: path={{ backup_dir }} state=directory mode=0755
      delegate_to: localhost

    - name: Pull email files from remote to local
      synchronize: src=/srv/www/current/files/ dest={{ backup_dir }}/files mode=pull

    - name: Pull cache files from remote to local
      synchronize: src=/srv/www/current/cache/{{ item }} dest={{ backup_dir }}/cache/{{ item }} mode=pull
      with_items:
        - attachments_development
        - attachments_production
      tags: backup_cache

    - name: Backup database
      shell: "sudo su - postgres -c 'pg_dump {{ alaveteli_database }} > /tmp/alaveteli.sql'"
      become_user: root
      args:
        creates: /tmp/alaveteli.sql

    - name: Pull database backup
      synchronize: src=/tmp/alaveteli.sql dest={{ backup_dir }}/alaveteli.sql mode=pull
