# Playbook for removing all the production data
---

- hosts: alaveteli
  vars_files:
    - roles/alaveteli/vars/encrypted.yml
    - roles/alaveteli/vars/main.yml
    - roles/andreaswolf.letsencrypt/defaults/main.yml

  vars:
    backup_dir: "/tmp/alaveteli"
  tasks:
    - name: Restart postgresql to drop all connections
      service: name=postgresql state=restarted

    - name: Drop pesty users index
      command: "su - postgres -c \"psql -d alaveteli -U alaveteli -c \\\"drop index users_email_index;\\\"\""

    - name: Update all public bodies to the admin email
      command: "su - postgres -c \"psql -d alaveteli -U alaveteli -c \\\"update {{ item.table }} set {{ item.field }}='{{ alaveteli_admin_email }}';\\\"\""
      with_items:
        -
          table: users
          field: email
        -
          table: public_bodies
          field: request_email

    - name: Set all passwords to admin
      command: "su - postgres -c \"psql -d alaveteli -U alaveteli -c \\\"update users set salt='701758564852000.4562614399355047', hashed_password='953fe2755eaa70d9bab9d972caa30e1f496d24c4';\\\"\""
      tags: admin_password
