# Playbook for development VMs on your local box
---

- hosts:
    - righttoknow.org.au.dev
    - electionleaflets.org.au.dev
  roles:
    - role: deploy-user
      github_users: ['mlandauer', 'henare']
    - role: ANXS.timezone
      timezone_zone: Australia/Sydney
    - role: jnv.unattended-upgrades
      unattended_automatic_reboot: true
    # Let's always install database backup scripts (even if we're not using one of the databases)
    # TODO This runs apt update. Fix this
    - role: MaximeThoonsen.autopostgresqlbackup
    - role: MaximeThoonsen.automysqlbackup

- hosts: righttoknow.org.au.dev
  roles:
    - {role: ANXS.postgresql, postgresql_ext_install_dev_headers: yes}
    - {role: abtris.nginx-passenger}
    - role: zzet.rbenv
      rbenv:
        env: user
        version: v0.4.0
        ruby_version: 2.0.0-p598
      rbenv_users:
        - deploy
    - righttoknow

- hosts: planningalerts.org.au.dev
  roles:
    # TODO: Fix 3 tasks always returned changed status https://github.com/ANXS/timezone/issues/1
    - role: ANXS.timezone
      timezone_zone: Australia/Sydney
    - role: deploy-user
      github_users: ['mlandauer', 'henare']
    - role: jnv.unattended-upgrades
      unattended_automatic_reboot: true
    - role: ANXS.mysql
      mysql_bind_address: '127.0.0.1'
      mysql_root_password: ''
      mysql_databases:
        - name: planningalerts
    - role: MaximeThoonsen.automysqlbackup
    - role: abtris.nginx-passenger
    - role: geerlingguy.git
    - role: rvm_io.rvm1-ruby
      rvm1_rubies:
        - ruby-2.0.0-p598
    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: rails
          path: "/srv/www/shared/log/*.log"
          options:
            - daily
            - rotate 30
            - compress
            - missingok
            - copytruncate
    - role: planningalerts

- hosts: electionleaflets.org.au.dev
  roles:
    - role: electionleaflets
