# Playbook for development VMs on your local box
---

- hosts: righttoknow.org.au.dev
  roles:
    - righttoknow

- hosts: planningalerts.org.au.dev
  roles:
    - planningalerts
  vars_files:
    - encrypted_vars/planningalerts.yml

- hosts: electionleaflets.org.au.dev
  roles:
    - electionleaflets

- hosts: theyvoteforyou.org.au.dev
  roles:
    - theyvoteforyou
