# Playbook for development VMs on your local box
---

- hosts:
    - righttoknow.org.au.dev
    - electionleaflets.org.au.dev
  roles:
    - role: deploy-user
      github_users: ['mlandauer', 'henare']
    - role: xcezx.aliases
      aliases:
        - {user: deploy, alias: root}
        - {user: root, alias: web-administrators@openaustralia.org}
    - role: ANXS.timezone
      timezone_zone: Australia/Sydney
    - role: jnv.unattended-upgrades
      unattended_automatic_reboot: true
    # Let's always install database backup scripts (even if we're not using one of the databases)
    # TODO This runs apt update. Fix this
    - role: MaximeThoonsen.autopostgresqlbackup
    - role: MaximeThoonsen.automysqlbackup

- hosts: righttoknow.org.au.dev
  roles:
    - righttoknow

- hosts: planningalerts.org.au.dev
  vars_files:
    - encrypted_vars/planningalerts.yml
  roles:
    # TODO: Fix 3 tasks always returned changed status https://github.com/ANXS/timezone/issues/1
    - role: ANXS.timezone
      timezone_zone: Australia/Sydney
    - role: deploy-user
      github_users: ['mlandauer', 'henare']
    - role: xcezx.aliases
      aliases:
        - {user: deploy, alias: root}
        - {user: root, alias: web-administrators@openaustralia.org}
    - role: jnv.unattended-upgrades
      unattended_automatic_reboot: true
    - role: ANXS.mysql
      mysql_bind_address: '127.0.0.1'
      mysql_root_password: ''
      mysql_databases:
        - name: planningalerts
    - role: MaximeThoonsen.automysqlbackup
    - role: abtris.nginx-passenger
    - role: geerlingguy.git
    - role: rvm_io.rvm1-ruby
      rvm1_rubies:
        - ruby-2.0.0-p598
    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: rails
          path: "/srv/www/shared/log/*.log"
          options:
            - daily
            - rotate 30
            - compress
            - missingok
            - copytruncate
    - role: Stouts.backup
      backup_gpg_pw: "{{ planningalerts_backup_gpg_pw }}"
      backup_target_user: "{{ planningalerts_backup_target_user }}"
      backup_target_pass: "{{ planningalerts_backup_target_pass }}"
      backup_max_age: 6M
      backup_profiles:
        - name: automysqlbackup
          schedule: 0 4 * * *
          source: /var/lib/automysqlbackup
          # TODO: Duplicity will be very confused if two different machines from the same stage try to backup
          target: "s3://s3.amazonaws.com/oaf-backups/planningalerts/{{ inventory_hostname }}"
    - role: planningalerts

- hosts: electionleaflets.org.au.dev
  roles:
    - role: electionleaflets
