# Playbook for development VMs on your local box
---

- hosts:
    - righttoknow.org.au.dev
    - electionleaflets.org.au.dev
    - planningalerts.org.au.dev
  roles:
    - role: deploy-user
      github_users: ['mlandauer', 'henare']
    - role: xcezx.aliases
      aliases:
        - {user: deploy, alias: root}
        - {user: root, alias: web-administrators@openaustralia.org}
    # TODO: Fix 3 tasks always returned changed status https://github.com/ANXS/timezone/issues/1
    - role: ANXS.timezone
      timezone_zone: Australia/Sydney
    - role: jnv.unattended-upgrades
      unattended_automatic_reboot: true
    # Let's always install database backup scripts (even if we're not using one of the databases)
    # TODO This runs apt update. Fix this
    - role: MaximeThoonsen.autopostgresqlbackup
    - role: MaximeThoonsen.automysqlbackup

- hosts: righttoknow.org.au.dev
  roles:
    - righttoknow

- hosts: planningalerts.org.au.dev
  roles:
    - role: planningalerts
  vars_files:
    - encrypted_vars/planningalerts.yml

- hosts: electionleaflets.org.au.dev
  roles:
    - role: electionleaflets
