# Playbook for development VMs on your local box
---
- hosts: righttoknow.org.au.dev
  roles:
    - {role: deploy-user, github_users: ['mlandauer', 'henare']}
    - {role: jnv.unattended-upgrades, unattended_automatic_reboot: true}
    - {role: ANXS.postgresql, postgresql_ext_install_dev_headers: yes}
    - {role: abtris.nginx-passenger}
    - {role: MaximeThoonsen.autopostgresqlbackup}
    - {role: zzet.rbenv}
    - righttoknow

- hosts: planningalerts.org.au.dev
  roles:
    - {role: deploy-user, github_users: ['mlandauer', 'henare']}
    - {role: jnv.unattended-upgrades, unattended_automatic_reboot: true}
    - planningalerts
