# Playbook for restoring your remote instance
---

- hosts: alaveteli
  vars_files:
    - roles/alaveteli/vars/encrypted.yml
    - roles/alaveteli/vars/main.yml
    - roles/andreaswolf.letsencrypt/defaults/main.yml

  vars:
    backup_dir: "/tmp/alaveteli"
  tasks:
    - name: Push email files from local to remote
      synchronize: src={{ backup_dir }}/files dest=/srv/www/current/ mode=push

    - name: Push database backup
      synchronize: dest=/tmp/alaveteli.sql src={{ backup_dir }}/alaveteli.sql mode=push

    - name: Stop nginx
      service: name=nginx state=stopped

    - name: Restart postgresql to drop all connections
      service: name=postgresql state=restarted

    - name: Drop old databse
      command: "su - postgres -c 'dropdb alaveteli'"
      ignore_errors: true

    - include: roles/alaveteli/tasks/create_postgresqldb.yml

    - name: Restore the backed up db
      command: "su - postgres -c 'psql -d alaveteli -U alaveteli -f /tmp/alaveteli.sql'"

    - name: Migrate the database to the latest schema
      command: "su - deploy -c 'cd /srv/www/current && RAILS_ENV=production bundle exec rake db:migrate'"
      notify: nginx restart

    #- name: Put rbenv in bashrc
    #  lineinfile:
    #    dest: /etc/bash.bashrc
    #    regexp: ".*rbenv.sh.*"
    #    line: "source /etc/profile.d/rbenv.sh"
    #    create: true
    #  tags: parse_raw_emails

    #- name: Parse raw emails
    #  shell: 'source /etc/profile.d/rbenv.sh && echo "IncomingMessage.all.each { |incoming_message| incoming_message.parse_raw_email!(true) }" | RAILS_ENV=production bundle exec rails c'
    #  #shell: "echo $PATH"
    #  args:
    #    chdir: "/srv/www/current"
    #    executable: /bin/bash
    #  tags: parse_raw_emails
    #  notify: nginx restart
    #  become: yes
    #  become_user: deploy

    #- name: Rebuild Xapian indes
    #  shell: 'source /etc/profile.d/rbenv.sh && RAILS_ENV=production bundle exec rake xapian:rebuild_index models="InfoRequestEvent"'
    #  args:
    #    chdir: "/srv/www/current"
    #    executable: /bin/bash
    #  tags: xapian
    #  notify: nginx restart
    #  become_user: deploy
    #  become: yes

    - name: Restart nginx
      service: name=nginx state=restarted
      tags: nginx
