# Playbook for restoring your remote instance
---

- hosts: alaveteli
  vars_files:
    - roles/alaveteli/vars/encrypted.yml
    - roles/alaveteli/vars/main.yml
    - roles/andreaswolf.letsencrypt/defaults/main.yml

  vars:
    backup_dir: "/tmp/alaveteli"
  tasks:
    - name: Push files to remote to local
      synchronize: src={{ backup_dir }}/files dest=/srv/www/current/files/ mode=push

    - name: Push database backup
      synchronize: dest=/tmp/alaveteli.sql src={{ backup_dir }}/alaveteli.sql mode=push

    - name: Stop nginx
      service: name=nginx state=stopped

    - name: Restart postgresql to drop all connections
      service: name=postgresql state=restarted

    - name: Drop old databse
      command: "su - postgres -c 'dropdb alaveteli'"
      ignore_errors: true

    - include: roles/alaveteli/tasks/create_postgresqldb.yml

    - name: Backup database
      command: "su - postgres -c 'psql -d alaveteli -f /tmp/alaveteli.sql'"

    - name: Start nginx
      service: name=nginx state=started
