# Playbook for development VMs on your local box
---

- hosts: alaveteli
  roles:
    - custom_modules
    - alaveteli
    - { role: 'route53dns', tags: [ 'dns' ] }
  vars_files:
    - roles/alaveteli/vars/encrypted.yml
