# Playbook for development VMs on your local box
---

- hosts: righttoknow
  roles:
    - custom_modules
    - righttoknow
    - { role: 'route53dns', tags: [ 'route53dns' ] }
  vars_files:
    - roles/righttoknow/vars/encrypted.yml