# Playbook for development VMs on your local box
---

- hosts: alaveteli
  roles:
    - { role: 'route53dns', tags: [ 'dns', 'nondev' ] }
    - custom_modules
    - alaveteli
  vars_files:
    - roles/alaveteli/vars/encrypted.yml
