---
- name: Ensure that deploy owns /srv/www
  file: owner=deploy group=deploy path=/srv/www state=directory

# Installing via bash so that rbenv is used. Otherwise would install gems for default system ruby
- name: Install bundler gem
  command: bash -lc "gem install bundler"
  sudo: true
  sudo_user: deploy

- name: Install libicu-dev for charlock_holmes gem used in alaveteli
  apt: name=libicu-dev state=present

- name: Install libmagic-dev for mahoro gem used in alaveteli
  apt: name=libmagic-dev state=present

- name: Install libmagickwand-dev for RMagick gem used in alaveteli
  apt: name=libmagickwand-dev state=present

- name: Install xapian-tools for Alaveteli
  apt: name=xapian-tools state=present

- name: Install uuid-dev for Alaveteli
  apt: name=uuid-dev state=present

- name: Create database
  postgresql_db: name=alaveteli

- name: Create posgresql role
  postgresql_user: db=alaveteli name=alaveteli password={{ db_password }}

- name: Copy over database configuration for application
  template: src=database.yml dest=/srv/www/shared/database.yml owner=deploy group=deploy
  notify: nginx restart
