---
- include_vars: encrypted.yml

- name: Ensure that deploy owns /srv/www and /srv/www/shared
  file:
    state: directory
    owner: deploy
    group: deploy
    path: '{{item}}'
  with_items:
    - /srv/www
    - /srv/www/shared

- name: Ensure packages to build gem native extensions are installed
  apt:
    pkg: '{{item}}'
  with_items:
    - libmysqlclient-dev
    - libxml2-dev
    - libxslt1-dev
    - sphinxsearch

- name: Copy application configuration
  template:
    src: "{{ item }}"
    dest: /srv/www/shared/
    owner: deploy
    group: deploy
  with_items:
    - configuration.rb
    - throttling.yml
  notify: nginx reload

- name: Copy static application configuration
  copy:
    src: '{{item}}'
    dest: /srv/www/shared/
    owner: deploy
    group: deploy
  with_items:
    - database.yml
    - production.sphinx.conf
    - sphinx.yml
  notify: nginx reload

- name: Copy self-signed development SSL certificate
  copy:
    src: planningalerts.org.au.dev.pem
    dest: /etc/ssl/
    owner: root
    group: root
    mode: 0644
  notify: nginx reload

- name: Copy self-signed development SSL key
  copy:
    content: "{{ planningalerts_development_ssl_key }}"
    dest: /etc/ssl/private/planningalerts.org.au.dev.key
    owner: root
    group: ssl-cert
    mode: 0640
  notify: nginx reload

- name: Copy nginx main configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/
  notify: nginx restart

- name: Copy test/test password for staging site
  copy:
    src: htpasswd
    dest: /etc/nginx/
  notify: nginx restart

- name: Copy nginx site configuration
  copy:
    src: default
    dest: /etc/nginx/sites-available/
  notify: nginx reload

- name: Copy application upstart service configuration
  copy:
    src: '{{item}}'
    dest: /etc/init/
  with_items:
    - planningalerts.conf
    - planningalerts-sphinx-1.conf
    - planningalerts-sphinx.conf
    - planningalerts-worker-1.conf
    - planningalerts-worker.conf

- name: Allow deploy user to control services
  copy:
    src: deploy_service_control
    dest: /etc/sudoers.d/
  notify: sudo reload

- name: Set up PlanningAlerts daily scrape and email job
  cron:
    name: planningalerts_scrape_and_email
    user: deploy
    hour: 12
    job: "cd /srv/www/current && /usr/local/bin/bundle exec rake planningalerts:applications:scrape_and_email RAILS_ENV=production"
