---
- include_vars: encrypted.yml

- name: Ensure that deploy owns /srv/www and /srv/www/shared
  file:
    state: directory
    owner: deploy
    group: deploy
    path: '{{item}}'
  with_items:
    - /srv/www
    - /srv/www/shared

- name: Ensure packages to build gem native extensions are installed
  apt:
    pkg: '{{item}}'
  with_items:
    - libmysqlclient-dev
    - libxml2-dev
    - libxslt1-dev
    - sphinxsearch

- name: Copy application configuration files
  template:
    src: '{{item}}'
    dest: /srv/www/shared/
    owner: deploy
    group: deploy
  with_items:
    - database.yml
    - throttling.yml
    - configuration.rb
    - production.sphinx.conf
    - sphinx.yml
  notify: nginx reload

- name: Copy nginx main configuration
  template:
    src: nginx.conf
    dest: /etc/nginx/
  notify: nginx restart

- name: Copy nginx site configuration
  template:
    src: default
    dest: /etc/nginx/sites-available/
  notify: nginx reload

- name: Copy application upstart service configuration
  copy:
    src: '{{item}}'
    dest: /etc/init/
  with_items:
    - planningalerts.conf
    - planningalerts-sphinx-1.conf
    - planningalerts-sphinx.conf
    - planningalerts-worker-1.conf
    - planningalerts-worker.conf

- name: Allow deploy user to control services
  copy:
    src: deploy_service_control
    dest: /etc/sudoers.d/
  notify: sudo reload
