---
galaxy_info:
  author: Hector Castro
  description: An Ansible role for installing ElasticSearch.
  company: Azavea Inc.
  license: Apache
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - system
  - monitoring
dependencies:
  - { role: "azavea.java" }
