---
# vars file for planningalerts
morph_api_key: "{{ encrypted_morph_api_key }}"
google_maps_key: "{{ encrypted_google_maps_key }}"
google_maps_client_id: "{{ encrypted_google_maps_client_id }}"
google_maps_cryptographic_key: "{{ encrypted_google_maps_cryptographic_key }}"
twitter_consumer_key: "{{ encrypted_twitter_consumer_key }}"
twitter_consumer_secret: "{{ encrypted_twitter_consumer_secret }}"
twitter_oauth_token: "{{ encrypted_twitter_oauth_token }}"
twitter_oauth_token_secret: "{{ encrypted_twitter_oauth_token_secret }}"
cuttlefish_user_name: "{{ encrypted_cuttlefish_user_name }}"
cuttlefish_password: "{{ encrypted_cuttlefish_password }}"
theme_nsw_host: "{{ encrypted_theme_nsw_host }}"
theme_nsw_email_from_address: "{{ encrypted_theme_nsw_email_from_address }}"
theme_nsw_email_from_name: "{{ encrypted_theme_nsw_email_from_name }}"
theme_nsw_cuttlefish_user_name: "{{ encrypted_theme_nsw_cuttlefish_user_name }}"
theme_nsw_cuttlefish_password: "{{ encrypted_theme_nsw_cuttlefish_password }}"
honeybadger_api_key: "{{ encrypted_honeybadger_api_key }}"
throttling_configuration: "{{ encrypted_throttling_configuration }}"
planningalerts_development_ssl_key: "{{ encrypted_planningalerts_development_ssl_key }}"
planningalerts_production_ssl_key: "{{ encrypted_planningalerts_production_ssl_key }}"
planningalerts_api_ssl_key: "{{ encrypted_planningalerts_api_ssl_key }}"
