---
- name: install build depends
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - libssl-dev
    - libyaml-dev
    - libreadline-dev
    - zlib1g-dev
    - libffi-dev
    - git
  become: true
  become_method: sudo
  become_user: "root"
  tags:
    - rbenv

