---
# tasks file for base-server
- name: Enable firewall and deny traffic by default
  ufw:
    state: enabled
    policy: deny
  tags: firewall
  become: true
  become_method: sudo
  become_user: "root"

- name: Allow rate-limited SSH trafic
  ufw:
    rule: limit
    port: ssh
    proto: tcp
  tags: firewall
  become: true
  become_method: sudo
  become_user: "root"

- name: Allow HTTP traffic
  ufw:
    rule: allow
    port: http
    proto: tcp
  tags: firewall
  become: true
  become_method: sudo
  become_user: "root"

- name: Allow extra HTTP traffic
  ufw:
    rule: allow
    port: 8080
    proto: tcp
  tags: firewall
  become: true
  become_method: sudo
  become_user: "root"

- name: Allow debug HTTP traffic
  ufw:
    rule: allow
    port: 3000
    proto: tcp
  tags: firewall
  become: true
  become_method: sudo
  become_user: "root"

- name: Allow HTTPS traffic
  ufw:
    rule: allow
    port: https
    proto: tcp
  tags: firewall
  become: true
  become_method: sudo
  become_user: "root"

- name: Allow SMTP traffic
  ufw:
    rule: allow
    port: smtp
    proto: tcp
  tags: firewall
  become: true
  become_method: sudo
  become_user: "root"

- name: Allow Varnish traffic
  ufw:
    rule: allow
    port: '{{ varnish_http_port }}'
    proto: tcp
  tags: varnish
  become: true
  become_method: sudo
  become_user: "root"

- name: Ensure git is installed
  apt:
    pkg: git
  become: true
  become_method: sudo
  become_user: "root"

# Setup timezone stuff

- name: Install tzdata package
  apt: pkg=tzdata state=present
  become: true
  become_method: sudo
  become_user: "root"

- name: Set timezone in /etc/timezone
  copy: content="{{ alaveteli_time_zone }}\n" dest=/etc/timezone
  notify: Update timezone
  become: true
  become_method: sudo
  become_user: "root"
