---
- name: Install packages required by Electionleaflets
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-imap
    - php5-gd
    - apache2
    - libapache2-mod-php5

# The rest of the deploy directories get created by running "cap deploy:setup"
- name: Ensure that deploy owns /srv/www and /srv/www/log
  file: path={{ item }} owner=deploy group=deploy state=directory
  with_items:
    - "/srv/www"
    - "/srv/www/log"

- name: Copy across the main apache config
  template: src=apache2.conf dest=/etc/apache2
  notify: reload apache

- name: Enable apache rewrite module
  apache2_module: state=present name=rewrite
  notify: reload apache

- name: Copy across the apache config
  template: src=electionleaflets.org.au.dev.conf dest=/etc/apache2/sites-available
  notify: reload apache

- name: Enable virtual host
  file: src="../sites-available/electionleaflets.org.au.dev.conf" dest="/etc/apache2/sites-enabled/electionleaflets.org.au.dev.conf" state=link
  notify: reload apache

- name: Disable default virtual host
  file: dest="/etc/apache2/sites-enabled/000-default.conf" state=absent
  notify: reload apache
