---
- include_vars: encrypted.yml

- name: Install packages required by Electionleaflets
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-imap
    - php5-gd
    - php5-mysql
    - apache2
    - libapache2-mod-php5

# The rest of the deploy directories get created by running "cap deploy:setup"
- name: Ensure that deploy owns /srv/www and /srv/www/log
  file: path={{ item }} owner=deploy group=deploy state=directory
  with_items:
    - "/srv/www"
    - "/srv/www/log"
    - "/srv/www/shared"
    - "/srv/www/shared/config"

# TODO Add a password to mysql root user

- name: Create mysql electionleaflets database
  mysql_db: name=electionleaflets state=present
  notify: reload apache

- name: Create mysql electionleaflets user
  mysql_user: name=electionleaflets password={{ db_password }} priv=electionleaflets.*:ALL state=present
  notify: reload apache

- name: Electionleaflets main config
  template: src=general.php dest=/srv/www/shared/config
  notify: reload apache

- name: Copy across the main apache config
  template: src=apache2.conf dest=/etc/apache2
  notify: reload apache

- name: Enable apache rewrite module
  apache2_module: state=present name=rewrite
  notify: reload apache

- name: Copy across the apache config
  template: src=electionleaflets.org.au.dev.conf dest=/etc/apache2/sites-available
  notify: reload apache

- name: Enable virtual host
  file: src="../sites-available/electionleaflets.org.au.dev.conf" dest="/etc/apache2/sites-enabled/electionleaflets.org.au.dev.conf" state=link
  notify: reload apache

- name: Disable default virtual host
  file: dest="/etc/apache2/sites-enabled/000-default.conf" state=absent
  notify: reload apache
