---
- name: Install packages required by Electionleaflets
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-imap
    - php5-gd
    - apache2
    - libapache2-mod-php5

# tasks file for electionleaflets
