---
- include_vars: encrypted.yml

- name: Install packages required by Electionleaflets
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-imap
    - php5-gd
    - php5-mysql
    - apache2
    - libapache2-mod-php5

# The rest of the deploy directories get created by running "cap deploy:setup"
- name: Ensure that directories exist
  file: path={{ item }} owner=deploy group=deploy state=directory
  with_items:
    - "/srv/www"
    - "/srv/www/log"
    - "/srv/www/shared"
    - "/srv/www/shared/config"

- name: Ensure that shared data directories exist and are writeable
  file: path={{ item }} owner=deploy group=www-data mode=775 state=directory
  with_items:
    - "/srv/www/shared/data"
    - "/srv/www/shared/data/smarty_compile"
    - "/srv/www/shared/data/smarty_compile"
    - "/srv/www/shared/data/cache"
    - "/srv/www/shared/data/temp"
    - "/srv/www/shared/data/images"
    - "/srv/www/shared/data/images/small"
    - "/srv/www/shared/data/images/original"
    - "/srv/www/shared/data/images/large"
    - "/srv/www/shared/data/images/medium"
    - "/srv/www/shared/data/images/thumbnail"

# TODO Add a password to mysql root user

- name: Create mysql electionleaflets database
  mysql_db: name=electionleaflets state=present
  notify: reload apache

- name: Create mysql electionleaflets user
  mysql_user: name=electionleaflets password={{ db_password }} priv=electionleaflets.*:ALL state=present
  notify: reload apache

- name: Electionleaflets main config
  template: src=general.php dest=/srv/www/shared/config
  notify: reload apache

- name: Copy across the main apache config
  template: src=apache2.conf dest=/etc/apache2
  notify: reload apache

- name: Enable apache rewrite module
  apache2_module: state=present name=rewrite
  notify: reload apache

- name: Copy across the apache config
  template: src=electionleaflets.org.au.dev.conf dest=/etc/apache2/sites-available
  notify: reload apache

- name: Enable virtual host
  file: src="../sites-available/electionleaflets.org.au.dev.conf" dest="/etc/apache2/sites-enabled/electionleaflets.org.au.dev.conf" state=link
  notify: reload apache

- name: Disable default virtual host
  file: dest="/etc/apache2/sites-enabled/000-default.conf" state=absent
  notify: reload apache

# TODO Only enable on production server or with separate config values
# - name: Cron for mail import
#   cron: name="mail import" minute="*/5" user=deploy job="cd /srv/www/current/tools && php import_mail.php" state=present

- name: Cron for email alerts
  cron: name="email alerts" minute="*/5" user=deploy job="cd /srv/www/current/tools && php alertomatic.php" state=present

- name: DNS setup
  dnsmadeeasy: account_key={{ dnsmadeeasy_key }} account_secret={{ dnsmadeeasy_secret }} domain="electionleaflets.org.au" record_ttl=1800 state=present record_name="{{ item.name }}" record_type="{{ item.type }}" record_value='{{ item.value }}'
  with_items:
    - {type: "A", name: "", value: "103.243.244.10"}
    - {type: "CNAME", name: "federal2010", value: ""}
    - {type: "CNAME", name: "test",        value: ""}
    - {type: "CNAME", name: "www",         value: ""}
    # TODO Do we need this record?
    - {type: "CNAME", name: "googleffffffffc7db8b0c", value: "google.com."}
    - {type: "HTTPRED", name: "tickets", value: "http://tickets.openaustraliafoundation.org.au/browse/EL"}
    - {type: "MX", name: "", value: "10 aspmx.l.google.com."}
    - {type: "MX", name: "", value: "20 alt1.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "20 alt2.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "30 aspmx2.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx3.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx4.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx5.googlemail.com."}
    - {type: "TXT", name: "", value: '"v=spf1 a include:_spf.google.com ~all"'}
