---
#acme_tiny_challenges_directory: "/srv/www/current/public"
alaveteli_host: "{{ inventory_hostname }}"
letsencrypt_certs:
 -
    name: "{{ alaveteli_host }}"
    keypath: "/etc/ssl/private/{{ alaveteli_host }}.key"
    certpath: "/etc/ssl/{{ alaveteli_host }}.crt"
    host: "{{ alaveteli_host }}"
db_password: "{{ encrypted_db_password }}"
alavateli_incoming_email_secret: '{{ encrypted_alavateli_incoming_email_secret }}'
alavateli_admin_password: '{{ encrypted_alavateli_admin_password }}'
alaveteli_cookie_store_session_secret: '{{ encrypted_alaveteli_cookie_store_session_secret }}'
alaveteli_recaptcha_public_key: '{{ encrypted_alaveteli_recaptcha_public_key }}'
alaveteli_recaptcha_private_key: '{{ encrypted_alaveteli_recaptcha_private_key }}'
righttoknow_development_ssl_key: '{{ encrypted_development_ssl_key }}'
righttoknow_test_ssl_key: '{{ encrypted_righttoknow_test_ssl_key }}'
righttoknow_production_ssl_key: '{{ encrypted_righttoknow_production_ssl_key }}'
# TODO These keys are replicated in the roles. Remove this duplication
route53_key: "{{ encrypted_route53_key }}"
route53_secret: "{{ encrypted_route53_secret }}"
