---
alaveteli_host: "{{ inventory_hostname }}"
letsencrypt_certs:
 -
    name: "{{ alaveteli_host }}"
    keypath: "/etc/ssl/private/{{ alaveteli_host }}.key"
    certpath: "/etc/ssl/{{ alaveteli_host }}.crt"
    host: "{{ alaveteli_host }}"
letsencrypt_user: 'letsencrypt'
letsencrypt_group: 'deploy'
alaveteli_database: 'alaveteli'
alaveteli_site_name: 'Nu Vă Supărați.info'
db_password: "{{ encrypted_db_password }}"
alavateli_incoming_email_secret: '{{ encrypted_alavateli_incoming_email_secret }}'
alavateli_admin_password: '{{ encrypted_alavateli_admin_password }}'
alaveteli_cookie_store_session_secret: '{{ encrypted_alaveteli_cookie_store_session_secret }}'
alaveteli_recaptcha_public_key: '{{ encrypted_alaveteli_recaptcha_public_key }}'
alaveteli_recaptcha_private_key: '{{ encrypted_alaveteli_recaptcha_private_key }}'
# TODO These keys are replicated in the roles. Remove this duplication
route53_key: "{{ encrypted_route53_key }}"
route53_secret: "{{ encrypted_route53_secret }}"
alaveteli_time_zone: "Europe/Bucharest"
alaveteli_admin_email: '{{ encrypted_alaveteli_admin_email }}'
github_users: ['andreicristianpetcu', 'petre2dor']
