---
- include_vars: encrypted_vars/dnsmadeeasy.yml

- name: Ensure that directories exist
  file: path={{ item }} owner=deploy group=deploy state=directory
  with_items:
    - "/srv/www/log"
    - "/srv/www/releases"
    - "/srv/www/shared/config"
    - "/srv/www/shared/images/mps"
    - "/srv/www/shared/images/mpsL"

- name: DNS setup for openaustralia.org.au
  dnsmadeeasy: account_key={{ dnsmadeeasy_key }} account_secret={{ dnsmadeeasy_secret }} domain="openaustralia.org.au" record_ttl=1800 state=present record_name="{{ item.name }}" record_type="{{ item.type }}" record_value='{{ item.value }}'
  tags:
    - dns
  with_items:
    - {type: "A", name: "",        value: "103.243.244.10"}
    - {type: "CNAME", name: "www", value:  ""}
    - {type: "CNAME", name: "data", value: ""}
    - {type: "MX", name: "", value: "10 aspmx.l.google.com."}
    - {type: "MX", name: "", value: "20 alt1.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "20 alt2.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "30 aspmx2.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx3.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx4.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx5.googlemail.com."}
    - {type: "TXT", name: "", value: '"v=spf1 a include:_spf.google.com ~all"'}

- name: DNS setup for openaustralia.org
  dnsmadeeasy: account_key={{ dnsmadeeasy_key }} account_secret={{ dnsmadeeasy_secret }} domain="openaustralia.org" record_ttl=1800 state=present record_name="{{ item.name }}" record_type="{{ item.type }}" record_value='{{ item.value }}'
  tags:
    - dns
  with_items:
    - {type: "A", name: "",        value: "103.243.244.10"}
    - {type: "A", name: "kedumba", value: "103.243.244.10"}
    - {type: "CNAME", name: "www",      value: "kedumba"}
    - {type: "CNAME", name: "test",     value: "kedumba"}
    # TODO Do blog redirect here rather than on the server
    - {type: "CNAME", name: "blog",     value: "kedumba"}
    - {type: "CNAME", name: "data",     value: "kedumba"}
    # TODO Redirect git here rather than on the server
    - {type: "CNAME", name: "git",      value: "kedumba"}
    - {type: "CNAME", name: "software", value: "kedumba"}
    # TODO Redirect wiki here rather than on the server
    - {type: "CNAME", name: "wiki",     value: "kedumba"}
    # TODO Do we need any of these google CNAMEs anymore?
    - {type: "CNAME", name: "calendar", value: "ghs.google.com."}
    - {type: "CNAME", name: "groups",   value: "ghs.google.com."}
    - {type: "CNAME", name: "hackfest", value: "ghs.google.com."}
    - {type: "CNAME", name: "mail",     value: "ghs.google.com."}
    - {type: "CNAME", name: "start",    value: "ghs.google.com."}
    - {type: "CNAME", name: "wave",     value: "ghs.google.com."}
    - {type: "HTTPRED", name: "tickets", value: "http://tickets.openaustraliafoundation.org.au"}
    - {type: "MX", name: "", value: "10 aspmx.l.google.com."}
    - {type: "MX", name: "", value: "20 alt1.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "20 alt2.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "30 aspmx2.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx3.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx4.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx5.googlemail.com."}
    - {type: "TXT", name: "", value: '"v=spf1 a include:_spf.google.com ~all"'}
    - {type: "TXT", name: "cuttlefish._domainkey", value: '"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnTduUSfwRbdTef45qgzmJ75zTtwiFgtadq/KFfY18/1plQiSSvzpOTNZQjuPW+5X9AeHQhPGtrxLd26ho/V/8FTj2YiAkpi0uwjPBMiERNhOYT9AJzImNpTmFaa9Sq2JXnhYJQHZhlEVu2iE3ZQEZ+3gIbgvS23vFSYwv3n3HwcbAo3epYCekVglKBZvbGvChXZvmN90wz""5ovTv74VPOiq96xPWkzcbA5CEiEGfJT8VqNdciQlbEy3Mpijyj/2qPvwZzDCG2xVS47FUr7xYXPRd/JUx7qDw+xlaFUQuT9S6/6zYWwJW7qJ4REIPvC/paORPfnsyqk8c6MIOH9nMXzQIDAQAB"'}
