- name: Ensure Postfix is installed
  apt: >
    name=postfix
    state=present
  become: true
  become_method: sudo
  become_user: "root"

- name: configure /etc/aliases
  lineinfile:
    dest: /etc/aliases
    line: "{{ item.user }}: {{ item.alias }}"
    regexp: "^{{ item.user }}:"
  with_items: "{{ aliases }}"
  notify: update aliases database
  become: true
  become_method: sudo
  become_user: "root"
