- name: Ensure we have a deploy group
  group: name=deploy
  become: true
  become_method: sudo
  become_user: "root"

- name: Ensure we have a deploy user
  user: name=deploy comment="Deploy user" shell=/bin/bash group=deploy
  become: true
  become_method: sudo
  become_user: "root"

- name: Add keys to deploy
  become: true
  become_method: sudo
  become_user: "root"
  authorized_key:
    user: deploy
    key: https://github.com/{{ item }}.keys
  with_items: "{{ github_users }}"
  register: add_authorized_keys

- name: Add keys to root
  become: true
  become_method: sudo
  become_user: "root"
  authorized_key:
    user: root
    key: https://github.com/{{ item }}.keys
  with_items: "{{ github_users }}"

- name: Only allow ssh access with keys
  lineinfile: dest=/etc/ssh/sshd_config state=present regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
  when: add_authorized_keys.changed
  notify: sshd restart
  become: true
  become_method: sudo
  become_user: "root"
