---
dependencies:
  - role: deploy-user
  - role: xcezx.aliases
    aliases:
      - {user: postmaster, alias: root}
      - {user: deploy, alias: root}
      - {user: root, alias: "admin@{{ alaveteli_host }}"}
      - {user: admin, alias: "{{ alaveteli_admin_email }}"}
      - {user: team, alias: "{{ alaveteli_admin_email }}"}
      - {user: user-support, alias: team}
      - {user: do-not-reply-to-this-address, alias: /dev/null}
    tags: aliases
  - role: ANXS.ntp
  - role: jnv.unattended-upgrades
    unattended_automatic_reboot: true
  # Let's always install database backup scripts (even if we're not using one of the databases)
  # TODO This runs apt update. Fix this
  - role: MaximeThoonsen.autopostgresqlbackup
