#!/bin/bash

# We want this script to run in the context of the ruby version defined for the site
# please see https://github.com/mysociety/alaveteli/blob/a2ba1dbe1aa64d3a371893a5f43fad6784364975/config/run-with-rbenv-path.example
RAILS_ENV=production
PATH=/home/deploy/.rbenv/bin:/home/deploy/.rbenv/shims:$PATH

source "$1"

exit $?
