---
- include_vars: encrypted_vars/dnsmadeeasy.yml

# TODO Extract php-mysql-apache role
- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - php5-mysql
    - apache2
    - libapache2-mod-php5
  notify: reload apache

- name: DNS setup for oaf.org.au
  dnsmadeeasy: account_key={{ dnsmadeeasy_key }} account_secret={{ dnsmadeeasy_secret }} domain="oaf.org.au" record_ttl=1800 state=present record_name="{{ item.name }}" record_type="{{ item.type }}" record_value='{{ item.value }}'
  tags:
    - dns
  with_items:
    - {type: "A", name: "", value: "103.243.244.10"}
    - {type: "A", name: "cuttlefish", value: "23.239.22.35"}
    - {type: "A", name: "kedumba", value: "103.243.244.10"}
    # TODO Do we need scraper anymore?
    - {type: "A", name: "scraper", value: "162.243.201.227"}
    - {type: "CNAME", name: "www",             value: ""}
    - {type: "CNAME", name: "test",            value: ""}
    # TODO Do we need publicwhip-test anymore?
    - {type: "CNAME", name: "publicwhip-test", value: ""}
    - {type: "CNAME", name: "tickets",         value: ""}
    - {type: "MX", name: "", value: "10 aspmx.l.google.com."}
    - {type: "MX", name: "", value: "20 alt1.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "20 alt2.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "30 aspmx2.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx3.googlemail.com."}
    - {type: "MX", name: "cuttlefish", value: "1 aspmx.l.google.com."}
    - {type: "MX", name: "cuttlefish", value: "5 alt1.aspmx.l.google.com."}
    - {type: "MX", name: "cuttlefish", value: "5 alt2.aspmx.l.google.com."}
    - {type: "MX", name: "cuttlefish", value: "10 aspmx2.googlemail.com."}
    - {type: "MX", name: "cuttlefish", value: "10 aspmx3.googlemail.com."}
    - {type: "TXT", name: "", value: '"v=spf1 a include:_spf.google.com ~all"'}
    - {type: "TXT", name: "", value: "google-site-verification=RLhe_zgIDJMxpFFYFewv0KaRlWQvH-JDBxxpEV-8noY"}
    - {type: "TXT", name: "cuttlefish", value: '"v=spf1 include:_spf.google.com ip4:23.239.22.35 ip6:2600:3c01::f03c:91ff:fe89:1913 -all"'}
    - {type: "TXT", name: "cuttlefish._domainkey.cuttlefish", value: '"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvEPfY69ZLYEn+I8rXaRLpTTb9c8AAEdjlUIPAX5nZ2cPYRxA8eCO/AYgXGXXdvGYWUm7sDkil6oSlqZjLx3au31AOoPNimi8FT2QjSgDp/Qkd403ACW314Aio4lo39y+un4GK0ih6KDuJAcxSftoGd9DFViBkVUs8Cs/WhFnc2dkhKTpCtt8Mji+bNtTOYsFwAg8LC3tDn""Wg+V3UTqqFQBi476DemGPVjxtpe48uFjCQpGg8T0uW54cIKWiC3PWCU0Ksj3HVMhE8P33McW/VFyGAx+nDlc0i6VY3zZi2i86O9Z84j0bJm/607lFK/pCa/Rv8hSJz5Ksk2EkD0NKh0QIDAQAB"'}

- name: DNS setup for openaustraliafoundation.org.au
  dnsmadeeasy: account_key={{ dnsmadeeasy_key }} account_secret={{ dnsmadeeasy_secret }} domain="openaustraliafoundation.org.au" record_ttl=1800 state=present record_name="{{ item.name }}" record_type="{{ item.type }}" record_value='{{ item.value }}'
  tags:
    - dns
  with_items:
    - {type: "A", name: "", value: "103.243.244.10"}
    - {type: "A", name: "kedumba", value: "103.243.244.10"}
    - {type: "CNAME", name: "www", value: ""}
    # TODO This is wrong - we don't have a staging server anymore
    - {type: "CNAME", name: "test", value: "kedumba" }
    # TODO We should get rid of kedumba-old-ip
    - {type: "A", name: "kedumba-old-ip", value: "122.100.2.212"}
    # TODO Do we need alaveteli-staging?
    - {type: "CNAME", name: "alaveteli-staging", value: "kedumba"}
    # TODO This is down right confusing. We should get rid of this cuttlefish record
    - {type: "CNAME", name: "cuttlefish", value: "kedumba"}
    # TODO I think we can get rid of people
    - {type: "CNAME", name: "people", value: "kedumba"}
    # TODO Can we get rid of publicwhip-rails and publicwhip-test?
    - {type: "CNAME", name: "publicwhip-rails", value: "kedumba"}
    - {type: "CNAME", name: "publicwhip-test", value: "kedumba"}
    - {type: "CNAME", name: "tickets", value: "kedumba"}
    - {type: "MX", name: "", value: "10 aspmx.l.google.com."}
    - {type: "MX", name: "", value: "20 alt1.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "20 alt2.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "30 aspmx2.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx3.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx4.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx5.googlemail.com."}
    # TODO I think this is completely wrong - pointing to a CNAME
    - {type: "MX", name: "kedumba", value: "10 kedumba"}
    - {type: "TXT", name: "", value: '"v=spf1 a include:_spf.google.com ~all"'}
